### ISSUE TITLE
Action is not fired

### ISSUE THREAD

**Issue by gonvaled** [Kuzirashi/ember-link-action#4]
The transition happens normally, but the action is not triggered. This is the template:

```
<li>{{#link-to "logout" invokeAction="invalidateSession"}}<i class="fa fa-sign-out"></i> LOGOUT{{/link-to}}</li>
```

The action is defined on the application route:

```
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
    session: Ember.inject.service('session'),

    actions: {
        invalidateSession: function() {
            this.get('session').invalidate();
        }
    }
});
```

The action is working fine with:

```
 <li><a href="#" {{action 'invalidateSession'}}><i class="fa fa-sign-out"></i> LOGOUT</a></li>
```

But with that I loose the link-to functionality, of course. Specifically, the whole application is reloaded (because the `a` tells the browser to navigate to another page I guess, even though I am using `href="#"`)

I am running Ember@2.2.0. I have installed ember-link-action@0.0.33. I am not sure ember-cli is automatically picking it up. Normally the
```
var app = new EmberApp(defaults, {
    // Add options here
});
```
should automatically package the necessary modules, right? (btw: what heuristics is `EmberApp` using to decide what to package?)

How can I verify if the ember-link-action package is included in the application?

**Comment by Kuzirashi** [comment]
I have restarted travis build to see if it works with recent Ember versions but it does work even with ember 2.3.0-beta.3.

Can you confirm actions is not fired? Maybe try putting `console.log` in `invalidateSession` and see.

You can also try using:

{{#link-to "logout" invokeAction=(action 'invalidateSession')}}

**Comment by Panman8201** [comment]
It's working for me with ember 2.3.0-beta.3. Just what I needed to make my sidebar links close the sidebar. Thanks!

**Comment by Kuzirashi** [comment]
@Panman8201 That's great to hear! :D I would appreciate if you could star this repo so I can get karma back. :D
