### ISSUE TITLE
Actions on the router

### ISSUE THREAD

**Issue by haldiggs** [Kuzirashi/ember-link-action#7]
if you get a chance to make this read the actions on the router it would be great. Current;y my global actions (Login, Logout) are on the application router. The ember input and link-to can use them.

**Comment by Baukereg** [comment]
Take a look at https://github.com/DockYard/ember-route-action-helper. Including this addon you can write:

```
{{#link-to 'other-route' invokeAction=(route-action 'testAction')}}
```

Where testAction is an action on the route.

**Comment by Kuzirashi** [comment]
I think it solves the issue - the solution from @Baukereg looks good. ;)
